import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider"
import Navbar from "@/components/navbar";
import { useTranslations } from "next-intl";
import { NavbarType } from "../../../interfaces/navbar-interface";
import Footer from "@/components/footer";
const poppins = Poppins({ weight: ["400", "700", "900", "800", "600", "500", "300", "200", "100"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params: { locale }
}: Readonly<{
  children: React.ReactNode; params: { locale: string };
}>) {
  const navigation: NavbarType[] = [
    { name: "Home", href: "/" },
    { name: "Products", href: "/products" },
    { name: "Contacts", href: "/contacts" },
  ];
  const t = useTranslations('Navbar');
  const indexT = useTranslations('Index')
  const navItems: NavbarType[] = navigation.map((nav: NavbarType) => {
    nav.name = t(nav.name)
    return nav
  })
  const navAllText = {
    changeLanguageText: indexT('changeLanguageText'),
    light: indexT('websiteMode.light'),
    dark: indexT('websiteMode.dark'),
    system: indexT('websiteMode.system')
  }
  return (
    <html lang={locale}>
      <body className={poppins.className}><ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Navbar locale={locale} navItems={navItems} navAllText={navAllText} />
        <div className="">
          {children}
        </div>
        <Footer />
      </ThemeProvider></body>
    </html>
  );
}
